#!/usr/bin/env bash

#    ____     ____    ____    __      __              
#   /\  _`\  /\  _`\ /\  _`\ /\ \  __/\ \  /'\_/`\    
#   \ \ \L\ \\ \,\L\_\ \ \L\ \ \ \/\ \ \ \/\      \   
#    \ \  _ <'\/_\__ \\ \ ,__/\ \ \ \ \ \ \ \ \__\ \  
#     \ \ \L\ \ /\ \L\ \ \ \/  \ \ \_/ \_\ \ \ \_/\ \ 
#      \ \____/ \ `\____\ \_\   \ `\___x___/\ \_\\ \_\
#       \/___/   \/_____/\/_/    '\/__//__/  \/_/ \/_/

# Important variables
read -r RICETHEME < "$HOME/.config/bspwm/.ricetheme"
export RICETHEME="xcad"
CONFIG_DIR="$HOME/.config/bspwm"
RICE_DIR="$CONFIG_DIR/bspwm/rices/$RICETHEME"
PATH="$HOME/.config/bspwm/scripts:$PATH"

export _JAVA_AWT_WM_NONREPARENTING=1

# Workspaces
workspaces() {
	name=1
	for monitor in $(bspc query -M); do
		bspc monitor "${monitor}" -n "$name" -d '1' '2' '3' '4' '5' '6'
		(( name++ ))
	done
}
workspaces

# BSWPM configuation
bspc config split_ratio                   0.51
bspc config single_monocle                true
bspc config borderless_monocle            false
bspc config gapless_monocle               false

bspc config focus_follows_pointer         true
bspc config pointer_follows_focus         false
bspc config pointer_motion_interval       5
bspc config pointer_modifier              mod4 
bspc config pointer_action1               move 
bspc config pointer_action2               resize_side 
bspc config pointer_action3               resize_corner

#bspc wm --adopt-orphans
bspc rule -a scratch sticky=on state=floating focus=on

# Set system variables
. SetSysVars

# Theme
. $RICE_DIR/theme.sh

# Wallpaper
feh -z --no-fehbg --bg-fill $RICE_DIR/wallpaper

# Picom
picom -b --config $CONFIG_DIR/picom.conf

# Sxhkd
sxhkd -c $CONFIG_DIR/sxhkdrc

# Dunst
dunst -config $CONFIG_DIR/dunst/dunstrc
